const config = {
  plugins: {
    "@tailwindcss/postcss": {
      theme: {
        extend: {
          fontFamily: {
            "headline-md": "var(--font-inter), sans-serif",
            "body-md": "var(--font-inter), sans-serif",
            "headline-lg": "var(--font-inter), sans-serif",
            display: "var(--font-inter), sans-serif",
            "body-lg": "var(--font-inter), sans-serif",
            "headline-lg-mobile": "var(--font-inter), sans-serif",
            "label-caps": "var(--font-jetbrains-mono), monospace",
            "code-sm": "var(--font-jetbrains-mono), monospace",
          },
          colors: {
            "surface-tint": "var(--color-surface-tint)",
            error: "var(--color-error)",
            "surface-container-low": "var(--color-surface-container-low)",
            "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
            background: "var(--color-background)",
            "on-secondary-container": "var(--color-on-secondary-container)",
            "on-background": "var(--color-on-background)",
            "secondary-fixed": "var(--color-secondary-fixed)",
            surface: "var(--color-surface)",
            "inverse-on-surface": "var(--color-inverse-on-surface)",
            "tertiary-fixed": "var(--color-tertiary-fixed)",
            "on-tertiary-fixed-variant":
              "var(--color-on-tertiary-fixed-variant)",
            "surface-container": "var(--color-surface-container)",
            tertiary: "var(--color-tertiary)",
            "surface-container-lowest": "var(--color-surface-container-lowest)",
            "on-primary-container": "var(--color-on-primary-container)",
            "error-container": "var(--color-error-container)",
            "inverse-surface": "var(--color-inverse-surface)",
            "outline-variant": "var(--color-outline-variant)",
            "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
            "on-surface-variant": "var(--color-on-surface-variant)",
            secondary: "var(--color-secondary)",
            "secondary-container": "var(--color-secondary-container)",
            outline: "var(--color-outline)",
            "surface-container-highest":
              "var(--color-surface-container-highest)",
            "on-tertiary-container": "var(--color-on-tertiary-container)",
            "on-error": "var(--color-on-error)",
            "on-secondary-fixed": "var(--color-on-secondary-fixed)",
            "on-primary": "var(--color-on-primary)",
            "surface-variant": "var(--color-surface-variant)",
            "surface-container-high": "var(--color-surface-container-high)",
            "primary-fixed-dim": "var(--color-primary-fixed-dim)",
            "surface-bright": "var(--color-surface-bright)",
            "primary-fixed": "var(--color-primary-fixed)",
            "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
            "inverse-primary": "var(--color-inverse-primary)",
            "on-tertiary": "var(--color-on-tertiary)",
            "surface-dim": "var(--color-surface-dim)",
            "on-secondary": "var(--color-on-secondary)",
            "on-surface": "var(--color-on-surface)",
            "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
            "tertiary-container": "var(--color-tertiary-container)",
            "on-secondary-fixed-variant":
              "var(--color-on-secondary-fixed-variant)",
            "primary-container": "var(--color-primary-container)",
            "on-error-container": "var(--color-on-error-container)",
            "on-primary-fixed": "var(--color-on-primary-fixed)",
            primary: "var(--color-primary)",
          },
        },
      },
    },
  },
};

export default config;
